[package]
name = "napi_craby_cli"
edition = { workspace = true }
version = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
craby_cli   = { path = "../../crates/craby_cli" }
napi        = { version = "3.3.0", default-features = false, features = ["napi10"] }
napi-derive = "3.2.5"
log         = { workspace = true }

[build-dependencies]
napi-build = "2.2.3"
